# Generated by Django 4.2.4 on 2023-08-15 09:28

from django.db import migrations
from django.conf import settings
from django.contrib.auth.hashers import make_password
import json

from django.db import transaction

@transaction.atomic
def add_user(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    users_data = open('fixtures/users.json')
    users_data = json.load(users_data)
    obj = []
    for user_data in users_data:
        is_superuser = False
        is_staff = False
        if 'is_superuser' in user_data:
            is_superuser = True
        if 'is_staff' in user_data:
            is_staff = True
        obj.append(User(
            id=user_data['id'],
            username=user_data['username'],
            first_name=user_data['name'],
            last_name=user_data['lastname'],
            email=user_data['email'],
            role=user_data['role'],
            password=make_password(user_data['password']),
            is_staff=is_staff,
            is_superuser=is_superuser
        ))
    User.objects.bulk_create(
        obj
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_user, ),
    ]
