# Generated by Django 4.2.4 on 2023-08-15 09:28

from django.db import migrations
from django.contrib.auth.hashers import make_password
from api.models import Payments
import json

from django.db import transaction

@transaction.atomic
def add_payments(apps, schema_editor):
    payments_data = open('fixtures/payments.json')
    payments_data = json.load(payments_data)
    obj = []
    for pay in payments_data:
        obj.append(Payments(
            user_id=pay['user_id'],
            product=pay['product'],
            price=pay['price'],
            currency=pay['currency'],
            pay_date=pay['pay_date'],
        ))
    Payments.objects.bulk_create(
        obj
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_payments'),
    ]

    operations = [
        migrations.RunPython(add_payments, ),
    ]
